### ISSUE TITLE
Suggestion: Allow toggling the display of the mod (if possible, auto toggle in the end).

### ISSUE THREAD

**Issue by Moire9** [symt/zealot-counter#19]
Hi, I enjoy this mod, however I do have one issue with it. There's no way to toggle the Display. I don't really want it in my view when I'm not using it, as it clutters the GUI, and I already have a fair bit of stuff there. A keybind or /zc option to toggle it would be nice, or, if possible have it auto-toggle in the End. I will warn you, if you try to do that, don't do it based off of the biome, as that will cause it to enable in the Graveyard because that uses the The End biome for the dark skies.

**Comment by symt** [comment]
This is being addressed [here](https://github.com/symt/zealot-counter/issues/10). Thanks for the suggestion though. It should be out in the next update.
