### ISSUE TITLE
Zealots killed with explosive bow are not counted

### ISSUE THREAD

**Issue by Antoine-dh** [symt/zealot-counter#24]

**Comment by hevex** [comment]
lol there is no way to fix this

**Comment by symt** [comment]
I'm starting development back up again. I know that this is an issue.

Possible fixes:
1. Use coin intake & combat xp from mobs to decide whether a zealot or not
2. Track arrow and see if explosion is where arrow lands (don't know if this is possible) and do something with that and zealots' item stands

Issues with those
1. Requires telekinesis
2. Arrows disappear immediately when they land.

In general, it's just a mess. This isn't top priority. If anyone wants to work on this, please lmk, make a fork of the repo, and make a PR when you're done.

**Comment by symt** [comment]
This is too much of a hassle for what it's worth. I might add it in the future but it is so far down the list that it's as good as dead.
