### ISSUE TITLE
Zealots number logging to file

### ISSUE THREAD

**Issue by minhperry** [symt/zealot-counter#25]
Hi, im wondering if the mod logs the statistics to any file somewhere, since I want to make a graph on it to track how im doing.

**Comment by symt** [comment]
Sorry for the delay. Are you looking for something like a list of zealot kills whenever eyes are found? Right now, the only data being saved is the bare minimum to display all of the info that is currently displayed.

**Comment by symt** [comment]
Since there hasn't been activity on this, I'm going to close the issue. If you have any more questions, open a new issue and I'll get right on it.
