### ISSUE TITLE
Problem on compiling own version

### ISSUE THREAD

**Issue by KacperPaszkowski** [symt/zealot-counter#32]
Hi,
I've tried compiling your code. I used Buildship to open your project in Eclipse. Then I've compiled those 3 java files and replaced files in original mod .jar file.
When I start Minecraft I'm getting error:

> net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraftforge.client.ClientCommandHandler.registerCommand(Lnet/minecraft/command/ICommand;)Lnet/minecraft/command/ICommand;

Or sometimes error about GetMinecraft() method.

**Comment by symt** [comment]
If you're using the gradle task "build," this shouldn't happen. It seems using shadowjar or jar does cause this to occur. I don't know why though.
